#pragma once

#include <SFML/Graphics.hpp>

// KeyCodes
#define KEY_A            sf::Keyboard::A
#define KEY_B            sf::Keyboard::B            
#define KEY_C            sf::Keyboard::C            
#define KEY_D            sf::Keyboard::D            
#define KEY_E            sf::Keyboard::E            
#define KEY_F            sf::Keyboard::F            
#define KEY_G            sf::Keyboard::G            
#define KEY_H            sf::Keyboard::H            
#define KEY_I            sf::Keyboard::I            
#define KEY_J            sf::Keyboard::J            
#define KEY_K            sf::Keyboard::K            
#define KEY_L            sf::Keyboard::L            
#define KEY_M            sf::Keyboard::M            
#define KEY_N            sf::Keyboard::N            
#define KEY_O            sf::Keyboard::O            
#define KEY_P            sf::Keyboard::P            
#define KEY_Q            sf::Keyboard::Q            
#define KEY_R            sf::Keyboard::R            
#define KEY_S            sf::Keyboard::S            
#define KEY_T            sf::Keyboard::T            
#define KEY_U            sf::Keyboard::U            
#define KEY_V            sf::Keyboard::V            
#define KEY_W            sf::Keyboard::W            
#define KEY_X            sf::Keyboard::X            
#define KEY_Y            sf::Keyboard::Y            
#define KEY_Z            sf::Keyboard::Z            
#define KEY_Num0         sf::Keyboard::Num0         
#define KEY_Num1         sf::Keyboard::Num1         
#define KEY_Num2         sf::Keyboard::Num2         
#define KEY_Num3         sf::Keyboard::Num3         
#define KEY_Num4         sf::Keyboard::Num4         
#define KEY_Num5         sf::Keyboard::Num5         
#define KEY_Num6         sf::Keyboard::Num6         
#define KEY_Num7         sf::Keyboard::Num7         
#define KEY_Num8         sf::Keyboard::Num8         
#define KEY_Num9         sf::Keyboard::Num9         
#define KEY_Escape       sf::Keyboard::Escape       
#define KEY_LControl     sf::Keyboard::LControl     
#define KEY_LShift       sf::Keyboard::LShift       
#define KEY_LAlt         sf::Keyboard::LAlt         
#define KEY_LSystem      sf::Keyboard::LSystem      
#define KEY_RControl     sf::Keyboard::RControl     
#define KEY_RShift       sf::Keyboard::RShift       
#define KEY_RAlt         sf::Keyboard::RAlt         
#define KEY_RSystem      sf::Keyboard::RSystem      
#define KEY_Menu         sf::Keyboard::Menu         
#define KEY_LBracket     sf::Keyboard::LBracket     
#define KEY_RBracket     sf::Keyboard::RBracket     
#define KEY_Semicolon    sf::Keyboard::Semicolon    
#define KEY_Comma        sf::Keyboard::Comma        
#define KEY_Period       sf::Keyboard::Period       
#define KEY_Quote        sf::Keyboard::Quote        
#define KEY_Slash        sf::Keyboard::Slash        
#define KEY_Backslash    sf::Keyboard::Backslash    
#define KEY_Tilde        sf::Keyboard::Tilde        
#define KEY_Equal        sf::Keyboard::Equal        
#define KEY_Hyphen       sf::Keyboard::Hyphen       
#define KEY_Space        sf::Keyboard::Space        
#define KEY_Enter        sf::Keyboard::Enter        
#define KEY_Backspace    sf::Keyboard::Backspace    
#define KEY_Tab          sf::Keyboard::Tab          
#define KEY_PageUp       sf::Keyboard::PageUp       
#define KEY_PageDown     sf::Keyboard::PageDown     
#define KEY_End          sf::Keyboard::End          
#define KEY_Home         sf::Keyboard::Home         
#define KEY_Insert       sf::Keyboard::Insert       
#define KEY_Delete       sf::Keyboard::Delete       
#define KEY_Add          sf::Keyboard::Add          
#define KEY_Subtract     sf::Keyboard::Subtract     
#define KEY_Multiply     sf::Keyboard::Multiply     
#define KEY_Divide       sf::Keyboard::Divide       
#define KEY_Left         sf::Keyboard::Left         
#define KEY_Right        sf::Keyboard::Right        
#define KEY_Up           sf::Keyboard::Up           
#define KEY_Down         sf::Keyboard::Down         
#define KEY_Numpad0      sf::Keyboard::Numpad0      
#define KEY_Numpad1      sf::Keyboard::Numpad1      
#define KEY_Numpad2      sf::Keyboard::Numpad2      
#define KEY_Numpad3      sf::Keyboard::Numpad3      
#define KEY_Numpad4      sf::Keyboard::Numpad4      
#define KEY_Numpad5      sf::Keyboard::Numpad5      
#define KEY_Numpad6      sf::Keyboard::Numpad6      
#define KEY_Numpad7      sf::Keyboard::Numpad7      
#define KEY_Numpad8      sf::Keyboard::Numpad8      
#define KEY_Numpad9      sf::Keyboard::Numpad9      
#define KEY_F1           sf::Keyboard::F1           
#define KEY_F2           sf::Keyboard::F2           
#define KEY_F3           sf::Keyboard::F3           
#define KEY_F4           sf::Keyboard::F4           
#define KEY_F5           sf::Keyboard::F5           
#define KEY_F6           sf::Keyboard::F6           
#define KEY_F7           sf::Keyboard::F7           
#define KEY_F8           sf::Keyboard::F8           
#define KEY_F9           sf::Keyboard::F9           
#define KEY_F10          sf::Keyboard::F10          
#define KEY_F11          sf::Keyboard::F11          
#define KEY_F12          sf::Keyboard::F12          
#define KEY_F13          sf::Keyboard::F13          
#define KEY_F14          sf::Keyboard::F14          
#define KEY_F15          sf::Keyboard::F15          
#define KEY_Pause        sf::Keyboard::Pause    

// MouseButtonCodes
#define MOUSE_1			 sf::Mouse::Button::Left
#define MOUSE_2			 sf::Mouse::Button::Right
#define MOUSE_3			 sf::Mouse::Button::Middle
